name: Repair
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8 #nmslib in pyserini only works python <= 3.9
  - pip
  - ftfy
  - rich
  - pandas
  - tqdm
  - openjdk=11
  - faiss-cpu=1.7.2
  - translators
  - pip:
      - pyserini==0.20.0
      - torch==1.13.0
      - ir_datasets==0.5.1
      - pandas==1.5.2
      - t5==0.9.3
      - tensorflow==2.11.0
      - protobuf==3.19.6
      - filesplit

